<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;
use App\Models\CmsTaxonomy;

class TaxonomyController extends Controller
{
    public function index(Request $request): Response
    {
        $s = $request->get('s');

        $items = CmsTaxonomy::select()
            ->where(function($query) use($s){
                if(!empty($s)){
                    $query->where('name', 'LIKE', '%'.str_replace(' ', '%', $s).'%');
                }
            })
            ->paginate(15);

        return Inertia::render('admin/taxonomies/index', [
            'items' => $items,
        ]);
    }

    public function create(): Response
    {
        return Inertia::render('admin/taxonomies/create');
    }

    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'slug' => 'nullable|string|max:255|unique:cms_taxonomies,slug',
            'description' => 'nullable|string',
            'active' => 'boolean',
        ]);

        $taxonomy = new CmsTaxonomy($request->all());
        // default slug will be auto-generated by sluggable if not provided
        $taxonomy->save();

        return redirect('admin/taxonomies');
    }

    public function edit($id): Response
    {
        $item = CmsTaxonomy::findOrFail($id);
        return Inertia::render('admin/taxonomies/edit', [
            'item' => $item,
        ]);
    }

    public function update($id, Request $request): RedirectResponse
    {
        $item = CmsTaxonomy::findOrFail($id);

        $request->validate([
            'name' => 'required|string|max:255',
            'slug' => 'nullable|string|max:255|unique:cms_taxonomies,slug,' . $id,
            'description' => 'nullable|string',
            'active' => 'boolean',
        ]);

        // If user clears the slug or updates name and slug is empty, let Sluggable re-generate it
        if (empty($request->slug)) {
            $item->slug = null;
        }

        $item->fill($request->except('slug'));
        if (!empty($request->slug)) {
            $item->slug = $request->slug;
        }
        $item->save();

        return redirect('admin/taxonomies');
    }

    public function destroy($id): RedirectResponse
    {
        $item = CmsTaxonomy::findOrFail($id);
        $item->delete();

        return redirect('admin/taxonomies');
    }
}
